version: '3.3'
services:
    root:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "${COMPOSE_PROJECT_NAME}_yarn_installer"
        working_dir: /app
        volumes:
            - .:/app
        command: >
            sh -c "
            npm run install:graphiql &&
            npm run build:graphiql"
