/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ExternalGraphqlPlaygroundConfiguration } from "./models/external-graphql-playground-configuration";
export { ExternalGraphqlPlaygroundConfiguration } from "./models/external-graphql-playground-configuration";
export namespace Components {
    interface GraphqlPlaygroundComponent {
        "configuration": ExternalGraphqlPlaygroundConfiguration;
        /**
          * Updates the language used in the GraphiQL component.
          * @param newLanguage - The new language to be set for the GraphiQL component. If not provided, it defaults to 'en'.
          * @returns A promise that resolves when the language is updated.
         */
        "setLanguage": (newLanguage: string) => Promise<void>;
    }
}
declare global {
    interface HTMLGraphqlPlaygroundComponentElement extends Components.GraphqlPlaygroundComponent, HTMLStencilElement {
    }
    var HTMLGraphqlPlaygroundComponentElement: {
        prototype: HTMLGraphqlPlaygroundComponentElement;
        new (): HTMLGraphqlPlaygroundComponentElement;
    };
    interface HTMLElementTagNameMap {
        "graphql-playground-component": HTMLGraphqlPlaygroundComponentElement;
    }
}
declare namespace LocalJSX {
    interface GraphqlPlaygroundComponent {
        "configuration"?: ExternalGraphqlPlaygroundConfiguration;
    }
    interface IntrinsicElements {
        "graphql-playground-component": GraphqlPlaygroundComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "graphql-playground-component": LocalJSX.GraphqlPlaygroundComponent & JSXBase.HTMLAttributes<HTMLGraphqlPlaygroundComponentElement>;
        }
    }
}
